explicit build dependency on graphviz for /usr/bin/dot
Apparently dot used to be pulled in by some doxygen package, but no longer.
This causes a FTBS issue.
See https://bugs.debian.org/798840

Running dot for graph 1/657
dot: not found
error: Problems running dot: exit code=127, command='dot', arguments='"/tmp/buildd/mlpack-1.0.12/obj-x86_64-linux-gnu/doc/html/core_8hpp__incl.dot" -Tpng -o "/tmp/buildd/mlpack-1.0.12/obj-x86_64-linux-gnu/doc/html/core_8hpp__incl.png"'
sh: 1: sh: 1: sh: 1: dot: not found